[workspace]
name      = "grits-env-pixi"
channels  = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[activation.env]
PYTHONPATH = "${PIXI_PROJECT_ROOT}/src"

# Base "CPU only" dependencies
[dependencies]
python       = "3.10.*"
pip          = "*"
numpy        = "*"
pandas       = "*"
scikit-learn = "*"
numba        = ">=0.61.2,<0.62"
wandb        = ">=0.21.0,<0.22"

[pypi-dependencies]
transformers = "*"
pytest       = "*"
pytest-cov   = "*"
lightning    = "*"
tqdm         = "*"
pysam        = "*"
torch        = "*"
torchvision  = "*"
tensorboard  = "*"


# "GPU only" dependencies (Linux and Windows)
[feature.gpu]
platforms = ["linux-64", "win-64"]

[feature.gpu.system-requirements]
cuda = "12"

[feature.gpu.dependencies]
cuda-version = "12.8.*"
cuda-toolkit = "*"

[feature.gpu.pypi-dependencies]
mamba-ssm = "*"
torch = "*"
torchvision = "*"


# Set up environments
[environments]
default = []      # pixi install
gpu     = ["gpu"] # pixi install --environment gpu

